# Generated by Django 3.2.12 on 2023-05-25 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalog_dish', models.CharField(default=0, max_length=30, verbose_name='Dish Name')),
                ('catalog_price', models.IntegerField(default=0, verbose_name='Dish Price')),
                ('catalog_description', models.CharField(default=0, max_length=100, verbose_name='Dish Description')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=30, verbose_name='Customer Full Name')),
                ('customer_status', models.BooleanField(default=0, max_length=30, verbose_name='Customer Status')),
                ('customer_address', models.CharField(default=0, max_length=30, verbose_name='Customer Address')),
                ('customer_contact', models.IntegerField(default=0, verbose_name='Customer Contact Number')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(default=0, max_length=30, verbose_name='Employee Name')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default='2023-05-25 10:30:00')),
                ('customer', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.customer')),
                ('employee', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.employee')),
                ('food', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.catalog')),
            ],
        ),
    ]
