# Generated by Django 3.2.12 on 2023-05-16 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='customer_premium',
            new_name='customer_type',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='customer_spendings',
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_location',
            field=models.CharField(default=0, max_length=30, verbose_name='Customer Loaction: '),
        ),
        migrations.AddField(
            model_name='order',
            name='catalog',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.catalog'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.customer'),
        ),
    ]
