# Generated by Django 3.2.12 on 2023-05-17 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20230516_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_location',
            field=models.CharField(default=0, max_length=30, verbose_name='Customer Location'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_name',
            field=models.CharField(max_length=30, verbose_name='Customer Full Name'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_type',
            field=models.BooleanField(default=0, max_length=30, verbose_name='Customer Type'),
        ),
    ]
