# Generated by Django 3.2.12 on 2023-05-23 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20230517_1310'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(default=0, max_length=30, verbose_name='Employee Name')),
            ],
        ),
        migrations.RemoveField(
            model_name='customer',
            name='customer_location',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='customer_type',
        ),
        migrations.RemoveField(
            model_name='order',
            name='catalog',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_type',
        ),
        migrations.AddField(
            model_name='catalog',
            name='catalog_description',
            field=models.CharField(default=0, max_length=100, verbose_name='Dish Description'),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_address',
            field=models.CharField(default=0, max_length=30, verbose_name='Customer Address'),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_contact',
            field=models.IntegerField(default=0, max_length=30, verbose_name='Customer Contact Number'),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_status',
            field=models.BooleanField(default=0, max_length=30, verbose_name='Customer Status'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='catalog_dish',
            field=models.CharField(default=0, max_length=30, verbose_name='Dish Name'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='catalog_price',
            field=models.IntegerField(default=0, max_length=30, verbose_name='Dish Price'),
        ),
        migrations.AddField(
            model_name='order',
            name='employee',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.employee'),
        ),
    ]
